version: "3.3"
services:
  app:
    image: clemenko/flask_demo:test
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
        #order: start-first
        failure_action: rollback
      mode: replicated
      placement:
        constraints:
          - 'node.role == worker'
      #  preferences:
      #    - spread: node.labels.availabilityZone
      labels:
          com.docker.lb.network: flask_kv
          com.docker.lb.hosts: app.dockr.life
          com.docker.lb.port: 5000
    ports:
      - 5000:5000
    networks:
      db:
      kv:
    secrets:
      - source: demo_title_v1
        target: demo_title

  mongo:
    image: mongo
    deploy:
      labels:
        com.docker.ucp.access.label: "/prod"
      placement:
        constraints:
          - 'node.role == worker'
    networks:
      db:

  redis:
    image: redis:alpine
    deploy:
      labels:
        com.docker.ucp.access.label: "/prod"
      placement:
        constraints:
          - 'node.role == worker'
    networks:
      kv:

networks:
  kv:
    labels:
      com.docker.ucp.access.label: "/prod"
  db:
    labels:
      com.docker.ucp.access.label: "/prod"
    driver: overlay
    driver_opts:
      encrypted: ""

secrets:
  demo_title_v1:
    external: true
