version: 3.4
services:
  redis.1:
    image: redis:alpine
    deploy:
      placement:
        constraints:
          - 'node.labels.redis_node == 1'
    volumes:
      - /opt/data:/data
    networks:
      redis:

  redis.2:
    image: redis:alpine
    deploy:
      placement:
        constraints:
          - 'node.labels.redis_node == 2'
    volumes:
      - /opt/data:/data
    networks:
      redis:

  redis.3:
    image: redis:alpine
    deploy:
      placement:
        constraints:
          - 'node.labels.redis_node == 3'
    volumes:
      - /opt/data:/data
    networks:
      redis:


networks:
  redis:
