version: "3.4"

x-updating:
  &parallel
  parallelism: 1
  delay: 10s
  order: start-first
  failure_action: rollback

services:
  app:
    image: clemenko/flask_demo
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
        reservations:
          cpus: '0.5'
          memory: 50M
      update_config: *parallel
      mode: replicated
    ports:
      - 5000:5000
    networks:
      db:
      kv:

  mongo:
    image: mongo
    networks:
      db:

  redis:
    image: redis:alpine
    networks:
      kv:

networks:
  kv:
  db:
