version: "3.7"

services:

  traefik:
    image: "traefik:v2.0.0-beta1"
    deploy:
      placement:
        constraints:
          - 'node.role == manager'
    command:
      #- "--log.level=DEBUG"
      - "--api=true"
      - '--providers.docker.endpoint="unix:///var/run/docker.sock"'
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"