version: "3.3"
services:
  traefik:
    image: traefik:2.0-alpine
    deploy:
      mode: global
      placement:
        constraints:
          - 'node.role == manager'
    ports:
      - 80:80
      - 8080:8080
      - protocol: tcp
      - mode: host
      
    networks:
      inbound:
    command:
      #- "--log.level=DEBUG"
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
#      - "-c /dev/null"
#      - "--web.metrics.prometheus --web.metrics.prometheus.buckets='0.1,0.3,1.2,5.0'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  inbound:
#    labels:
#      com.docker.ucp.access.label: "prod"
#    external: true
#  driver_opts:
#    encrypted: true
